# Creating NumPy Arrays

## Objective

Learn different ways to create NumPy arrays using built-in NumPy functions.

In [ ]:
## 1. Create an Array from a Python List

In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
## 2. Create an Array of Zeros

In [2]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones([1,3])

array([[1., 1., 1.]])

In [4]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

## Key Takeaways

- np.array() creates arrays from Python lists.
- np.zeros() creates arrays filled with zeros.
- np.ones() creates arrays filled with ones.
- np.full() fills an array with a specific value.
- np.eye() creates an identity matrix.
- np.arange() creates evenly spaced values.