# NumPy Mathematical Operations

## Objective

Learn how to perform element-wise mathematical operations on NumPy arrays.

### Topics Covered
- Array Arithmetic
- Addition
- Multiplication
- Division
- Floor Division
- Power
- Array Addition
- Trigonometric Functions

In [4]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
a + 2

array([3, 4, 5, 6])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a // 2

array([0, 1, 1, 2])

In [8]:
a ** 2

array([ 1,  4,  9, 16])

In [9]:
b = np.array([9,8,7,6])

b

array([9, 8, 7, 6])

In [10]:
c = a + b

c

array([10, 10, 10, 10])

In [11]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
d = np.array([30,45,60,90])

d

array([30, 45, 60, 90])

In [16]:
np.cos(d)

array([ 0.15425145,  0.52532199, -0.95241298, -0.44807362])