# NumPy Linear Algebra

## Objective

Learn the basic linear algebra operations provided by NumPy.

### Topics Covered

- Matrix Multiplication
- Identity Matrix
- Determinant of a Matrix

In [1]:
import numpy as np

In [2]:
# Matrix Multiplication

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [3]:
# Identity Matrix

c = np.identity(3)

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
# Determinant

np.linalg.det(c)

np.float64(1.0)