# NumPy Array Reshaping and Stacking

## Objective

Learn how to reshape arrays and combine multiple arrays.

### Topics Covered

- Reshape
- Vertical Stack
- Horizontal Stack

In [1]:
import numpy as np

In [2]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

after = before.reshape((2,2,2))

print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Vertical Stack

l1 = np.array([1,2,3,4])

l2 = np.array([5,6,7,8])

np.vstack([l1,l2,l1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [4]:
# Horizontal Stack

h1 = np.ones((2,4))

h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])